<b>Basics of Numpy



In [67]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Revise Lists in Python
(their indexing as well) 

In [68]:
a = [1,2,3,4,5]
print(a[1])
print(a[-5]) 
print(a[1:3])

2
1
[2, 3]


<b>Arrays in Numpy</b> <br>
Syntax: `np.array([array_elements])`<br>
The numpy arrays work similar to that of lists and index accessing is easily done <br>

In [69]:
import numpy as np 
a = np.array([1,2,3,4,5])
print(a)
print(a[-3:]) 
print(type(a))

[1 2 3 4 5]
[3 4 5]
<class 'numpy.ndarray'>


<b>Multi-Dimensional arrays <br>
Syntax: `np.array([[array_elements1],
                  [array_elements2],
                  [array_elements3]  
])` 


In [70]:
mul_array = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]
                    ])

print(mul_array)
print(mul_array[1])  #gets the specific array row
print(mul_array[1,2]) #gets the specific array element

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6


<b> Array Attribuetes</b> <br>
Numpy is written in C uses static code and hence there are occurences of datatypes and others which may feel irrelevant in python 

In [71]:
print(mul_array.shape) #gives out the dimensions of the matrix
print(mul_array.ndim) #depth of the matrix is given
print(mul_array.size) #total elements in array
print(mul_array.dtype) #returns the datatype of the elements in the numpy array 

(3, 3)
2
9
int32


<b>DataTypes in Numpy</b><br>
The explicit conversion of np.arrays can also be done in this way as well where you specify to U type <br>
`mix_array = np.array([[1,2,'1'],
             [1,2,4.6], 
             [4,5,'5'], 
             ] ,dtype= "<U5")` <br>
Change the code and see what happens with this type of array being used !<br>
also if any dictionary is being used in a `np.array` the `dtype` becomes object and the types are reverted back into the python datatypes not the numpy datatypes we had seen.  

In [72]:
mix_array = np.array([[1,2,'1'],
             [1,2,4.6], 
             [4,5,'5'], 
             ] ,dtype= np.float32)  

print(mix_array.dtype)     
print(mix_array[0][2].dtype) 
print(mix_array[0][2]) 

float32
float32
1.0


<b>Filling Arrays using `.full`</b><br>
Generating and filling the arrays of any dimension with number of your choice! <br>
<b>Syntax: </b> `array_name = np.full((shape_of_array), number_to_fill)`<br>
Shape of array is basically in form of (depth,no.of rows in a single array, no.of elements in a row ) (for understanding only not a deifinition )

In [73]:
new_arr  = np.full((4,5,6),5)
print(new_arr)

[[[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]]


Filling using `.zeroes` and `.ones` and also some other methods 

In [74]:
a1 = np.zeros((2,3,4))
a2 = np.ones((2,3,4))
a3 = np.empty((2,3,4))

print(a1)
print(a2)
print(a3)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0.5810299  0.54569189 0.75847441 0.13670079]
  [0.55871361 0.52601733 0.95445305 0.83657105]
  [0.99187807 0.82345153 0.69306706 0.7855674 ]]

 [[0.11745174 0.22938879 0.41074224 0.62260025]
  [0.67445339 0.44911371 0.15496663 0.00523975]
  [0.1974766  0.51398367 0.34600064 0.69823268]]]


Few more filling techniques using `.arange` and `.linspace` methods <br>
The `.arange` method  <b>Syntax: </b> `.arange(start_value, end_value, step_size)`<br>
The `.linspace` method <b>Syntax: </b> `.linspace(start_value, end_value, no_of_steps)` <br>
The `.linspace` methof divides it according to total no. of steps and the `.arange` uses the value of each step. 

In [75]:
array_1 = np.arange(0,100,4) 
array_2 = np.linspace(0,100,5)

print(array_1)
print(array_2)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]
[  0.  25.  50.  75. 100.]


Using <b>Nan</b> and <b>Inf</b> <br>
`np.nan` is used to represent the missing values in the data. <br>
`np.inf` is used to represent the infinite values in the data.

In [76]:
array_3 = np.random.rand(2,3,4)
print(array_3)
print(np.isnan(array_3))
print(np.isinf(array_3))    

print(np.sqrt(-1))
print(np.array([10])/0)

[[[0.14931106 0.39420267 0.42059412 0.53367154]
  [0.37099243 0.29073983 0.98888749 0.34190732]
  [0.77959404 0.45977254 0.720108   0.09116644]]

 [[0.90851023 0.56432859 0.50788983 0.38327196]
  [0.11291317 0.23480689 0.66530074 0.11170503]
  [0.58783831 0.71442038 0.33740172 0.13681235]]]
[[[False False False False]
  [False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]]]
[[[False False False False]
  [False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]]]
nan
[inf]


C:\Users\Praney KR\AppData\Local\Temp\ipykernel_5376\1807580794.py:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\Praney KR\AppData\Local\Temp\ipykernel_5376\1807580794.py:7: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


<b>Mathematical Operations</b><br>
The mathematical operations are easily done in numpy arrays and the operations are broadcasted to each element in the array. <br>
Below, there is a sharp contrast b/w how a numpy array works with mathemetical operations and how a list works with mathematical operations.

In [77]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

print(l1+l2)
print(np.array(l1)+np.array(l2))
print("****************")
print(l1*5)
print(np.array(l1)*5)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 7  9 11 13 15]
****************
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]


<b>Array Methods</b> <br>
There are many methods in numpy arrays which can be used to perform various operations on the arrays. <br>
The `.append` method is used to append the elements in the array. <br>
Syntax: `array_name.append(element)` <br>
The `.insert` method is used to insert the elements in the array. <br>
Syntax: `array_name.insert(index, element)` <br>
The `.delete` method is used to delete the elements in the array. <br>
Syntax: `array_name.delete(index)` <br>

In [78]:
array_1 = np.array([1,2,3,4,5])

print(array_1)

array_2 = np.array([6,7,8,9,10])

print(np.append(array_1,array_2))

array_1=np.insert(array_1,1,67) 
print(array_1)

print(np.delete(array_1,1))

array_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.delete(array_3,1,axis=1))

[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1 67  2  3  4  5]
[1 2 3 4 5]
[[1 3]
 [4 6]
 [7 9]]


<b>Structuring Methods</b> <br>
The `.reshape` method is used to reshape the array into the desired shape. <br>
Syntax: `array_name.reshape(shape)` <br>
The `.ravel` method is used to convert the multi-dimensional array into a single dimensional array. <br>
Syntax: `array_name.ravel()` <br>
The `.flatten` method is used to convert the multi-dimensional array into a single dimensional array. <br>
Syntax: `array_name.flatten()` <br>
The `.transpose` method is used to transpose the array. <br>
Syntax: `array_name.transpose()` <br>
The `.swapaxes` method is used to swap the axes of the array. <br>
Syntax: `array_name.swapaxes(axis1, axis2)` <br>

In [79]:
array_4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array_4.shape)
print(array_4.reshape(4,3))
print(array_4.reshape((4,3,1)))

array_1 = np.array([1,2,3,4,5])
print(array_4.flatten())
print(array_4.ravel())


array_2 = np.array([[2,4,6],[8,10,12],[14,16,18]])
print(array_2.transpose())

array_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_3.swapaxes(0,1))

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


<i>Difference b/w `.ravel` and `.flatten`</i><br>
It is that `.ravel` returns the reference of the original array and `.flatten` returns the copy of the original array. 


In [80]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

flattened_ravel = array_2d.ravel()
flattened_ravel[0] = 99  

flattened_flatten = array_2d.flatten()
flattened_flatten[1] = 98  

print("Original array after ravel modification:")
print(array_2d)
print("Flattened array with ravel():")
print(flattened_ravel)
print("Flattened array with flatten():")
print(flattened_flatten)

Original array after ravel modification:
[[99  2  3]
 [ 4  5  6]]
Flattened array with ravel():
[99  2  3  4  5  6]
Flattened array with flatten():
[99 98  3  4  5  6]


<b>Concatenation</b> <br>
The concatenation of the arrays can be done using the `.concatenate` method. <br>
Syntax: `np.concatenate([array1, array2], axis=0)` <br>
The `axis=0` is used to concatenate the arrays row-wise and `axis=1` is used to concatenate the arrays column-wise.

In [81]:
array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array_2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])

print(np.concatenate((array_1,array_2),axis=1)) 

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


<b>Stack</b><br>
The stacking of the arrays can be done using the `.stack` method. <br>
Syntax: `np.stack([array1, array2])` <br>

In [82]:
array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array_2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])

print(np.vstack((array_1,array_2)))
print(np.hstack((array_1,array_2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


<b>Split Command</b> <br>
The splitting of the arrays can be done using the `.split` method. <br>
Syntax: `np.split(array_name, indices_or_sections, axis=0)` <br>
However `indices_or_sections` is the number of splits and `axis` is the axis along which the array is split, and the no. of splits must be in such a way that it always makes certain equal portions.

In [83]:
a_1 = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20]])
a_1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

print(np.split(a_1, [6], axis=1))

print(np.split(a_1, [2], axis=1))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]]), array([], shape=(4, 0), dtype=int32)]
[array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]]), array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])]


<b>Aggregate Functons</b> <br>
The aggregate functions are used to perform the operations on the arrays. <br>
The `.sum` method is used to calculate the sum of the elements in the array. <br>
Syntax: `array_name.sum()` <br>
The `.min` method is used to calculate the minimum of the elements in the array. <br>
Syntax: `array_name.min()` <br>
The `.max` method is used to calculate the maximum of the elements in the array. <br>
Syntax: `array_name.max()` <br>
The `.mean` method is used to calculate the mean of the elements in the array. <br>
Syntax: `array_name.mean()` <br>
The `.median` method is used to calculate the median of the elements in the array. <br>
Syntax: `np.median(array_name)` <br>
The `.std` method is used to calculate the standard deviation of the elements in the array. <br>
Syntax: `array_name.std()` <br>

In [84]:
array_new = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array_new.sum())
print(array_new.min())
print(array_new.max())
print(array_new.mean())
print(array_new.std())


45
1
9
5.0
2.581988897471611


<b>Numpy Random </b> <br>
The numpy random module is used to generate the random numbers. <br>
The `.rand` method is used to generate the random numbers. <br>
Syntax: `np.random.rand(shape)` <br>
The `.randint` method is used to generate the random integers. <br>
Syntax: `np.random.randint(start, end, size=shape)` <br>
The `.randn` method is used to generate the random numbers from the standard normal distribution. <br>
Syntax: `np.random.randn(shape)` <br>
The `.choice` method is used to generate the random samples from the array. <br>
Syntax: `np.random.choice(array_name, size=shape)` <br>
The `.shuffle` method is used to shuffle the elements in the array. <br>
Syntax: `np.random.shuffle(array_name)` <br>
The `.permutation` method is used to randomly permute the sequence of the array. <br>
Syntax: `np.random.permutation(array_name)` <br>



In [87]:
randn = np.random.randn(2,3,4) #normal distribution
rand1 = np.random.randint(1,100,10) #random integers
rand2  = np.random.choice(2,3,4) #random choice
rand3 = np.random.shuffle(rand1) #shuffling the array
randp = np.random.permutation(10) #permutation of the array

print(randn)
print(rand1)
print(rand2)
print(rand3)
print(randp)


[[[-1.77567349 -1.05486155  1.07520844  0.19232858]
  [-1.68128779  1.12021356 -0.02565128  1.04473286]
  [-1.32949074 -1.02394315  0.77770865  0.15335912]]

 [[ 0.32009826 -0.14837591  2.73005679 -0.1794062 ]
  [ 0.01323288 -0.40875581 -1.69580223 -0.05474605]
  [-0.54504455  0.54203779  1.80096564  0.70862843]]]
[74 42 76 44 47 78 82 16 90 63]
[0 1 1]
None
[1 9 4 5 3 7 6 8 2 0]


<b>Exports and Imports</b> <br>
The `.save` method is used to save the array in the file. <br>
Syntax: `np.save('file_name', array_name)` <br>
The `.load` method is used to load the array from the file. <br>
Syntax: `np.load('file_name.npy')` <br>
The `.savetxt` method is used to save the array in the text file. <br>
Syntax: `np.savetxt('file_name.txt', array_name, delimiter=' ')` <br>
The `.loadtxt` method is used to load the array from the text file. <br>
Syntax: `np.loadtxt('file_name.txt', delimiter=' ')` <br>

In [92]:
array_new = np.array([[1,2,3],[4,5,6],[7,8,9]])

#uncomment line by line to see how to Import and Export Numpy Arrays
# np.save('array_new.npy',array_new)
# print('Array saved')
# array_loaded = np.load('array_new.npy')
# print('array loaded')
# print(array_loaded)
# array_csv = np.savetxt('array_new.csv',array_new,delimiter=',')
# print('Array saved')
# array_loaded = np.loadtxt('array_new.csv',delimiter=',')
# print(array_loaded)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
